# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NuGet Pack & Push

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:      
    
jobs:
  build:
    name: 'PackPush'
    runs-on: windows-latest
    
    env:
      Configuration: Release
      Solution: TG.Common.WinForms.sln
      PkgProject: src\TG.Common.WinForms\TG.Common.WinForms.csproj

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution /t:Restore /p:Configuration=$env:Configuration

    - name: Pack
      run: msbuild $env:PkgProject /t:pack /p:Configuration=$env:Configuration
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_KEY }}

    - name: Push to NuGet.org
      run: dotnet nuget push src\TG.Common\bin\Release\*.nupkg --api-key "$env:NUGET_TOKEN" --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_KEY }}

    - name: Push symbol package to NuGet.org
      run: dotnet nuget push src\TG.Common\bin\Release\*.snupkg --api-key "$env:NUGET_TOKEN" --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_KEY }}